/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CouponQuerySchema
 */
export interface CouponQuerySchema {
    /**
     * 
     * @type {Date}
     * @memberof CouponQuerySchema
     */
    day?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof CouponQuerySchema
     */
    member_id?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof CouponQuerySchema
     */
    usable?: boolean | null;
}

/**
 * Check if a given object implements the CouponQuerySchema interface.
 */
export function instanceOfCouponQuerySchema(value: object): value is CouponQuerySchema {
    return true;
}

export function CouponQuerySchemaFromJSON(json: any): CouponQuerySchema {
    return CouponQuerySchemaFromJSONTyped(json, false);
}

export function CouponQuerySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponQuerySchema {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'] == null ? undefined : (new Date(json['day'])),
        'member_id': json['member_id'] == null ? undefined : json['member_id'],
        'usable': json['usable'] == null ? undefined : json['usable'],
    };
}

export function CouponQuerySchemaToJSON(value?: CouponQuerySchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'day': value['day'] == null ? undefined : ((value['day'] as any).toISOString().substring(0,10)),
        'member_id': value['member_id'],
        'usable': value['usable'],
    };
}

