/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateSolutionSchema
 */
export interface CreateSolutionSchema {
  /**
   *
   * @type {number}
   * @memberof CreateSolutionSchema
   */
  problem_id: number;
  /**
   *
   * @type {string}
   * @memberof CreateSolutionSchema
   */
  comment: string;
  /**
   *
   * @type {string}
   * @memberof CreateSolutionSchema
   */
  source_code: string;
  /**
   *
   * @type {string}
   * @memberof CreateSolutionSchema
   */
  source_lang: string;
  /**
   *
   * @type {boolean}
   * @memberof CreateSolutionSchema
   */
  is_correct_answer: boolean;
  /**
   *
   * @type {Date}
   * @memberof CreateSolutionSchema
   */
  submitted_at?: Date | null | string;
  /**
   *
   * @type {boolean}
   * @memberof CreateSolutionSchema
   */
  star?: boolean;
}

/**
 * Check if a given object implements the CreateSolutionSchema interface.
 */
export function instanceOfCreateSolutionSchema(value: object): value is CreateSolutionSchema {
  if (!('problem_id' in value) || value['problem_id'] === undefined) return false;
  if (!('comment' in value) || value['comment'] === undefined) return false;
  if (!('source_code' in value) || value['source_code'] === undefined) return false;
  if (!('source_lang' in value) || value['source_lang'] === undefined) return false;
  if (!('is_correct_answer' in value) || value['is_correct_answer'] === undefined) return false;
  return true;
}

export function CreateSolutionSchemaFromJSON(json: any): CreateSolutionSchema {
  return CreateSolutionSchemaFromJSONTyped(json, false);
}

export function CreateSolutionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSolutionSchema {
  if (json == null) {
    return json;
  }
  return {
    problem_id: json['problem_id'],
    comment: json['comment'],
    source_code: json['source_code'],
    source_lang: json['source_lang'],
    is_correct_answer: json['is_correct_answer'],
    submitted_at: json['submitted_at'] == null ? undefined : new Date(json['submitted_at']),
    star: json['star'] == null ? undefined : json['star'],
  };
}

export function CreateSolutionSchemaToJSON(value?: CreateSolutionSchema | null): any {
  if (value == null) {
    return value;
  }
  return {
    problem_id: value['problem_id'],
    comment: value['comment'],
    source_code: value['source_code'],
    source_lang: value['source_lang'],
    is_correct_answer: value['is_correct_answer'],
    submitted_at: value['submitted_at'] == null ? undefined : (value['submitted_at'] as any).toISOString().substring(0, 10),
    star: value['star'],
  };
}
