/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';

/**
 * 
 * @export
 * @interface ErrorSchema
 */
export interface ErrorSchema {
    /**
     * 
     * @type {ErrorCode}
     * @memberof ErrorSchema
     */
    code: ErrorCode;
    /**
     * 
     * @type {string}
     * @memberof ErrorSchema
     */
    message: string;
    /**
     * 
     * @type {any}
     * @memberof ErrorSchema
     */
    details?: any | null;
}



/**
 * Check if a given object implements the ErrorSchema interface.
 */
export function instanceOfErrorSchema(value: object): value is ErrorSchema {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ErrorSchemaFromJSON(json: any): ErrorSchema {
    return ErrorSchemaFromJSONTyped(json, false);
}

export function ErrorSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'code': ErrorCodeFromJSON(json['code']),
        'message': json['message'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function ErrorSchemaToJSON(value?: ErrorSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': ErrorCodeToJSON(value['code']),
        'message': value['message'],
        'details': value['details'],
    };
}

