/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginSchema
 */
export interface LoginSchema {
    /**
     * 
     * @type {string}
     * @memberof LoginSchema
     */
    username: string;
}

/**
 * Check if a given object implements the LoginSchema interface.
 */
export function instanceOfLoginSchema(value: object): value is LoginSchema {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function LoginSchemaFromJSON(json: any): LoginSchema {
    return LoginSchemaFromJSONTyped(json, false);
}

export function LoginSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function LoginSchemaToJSON(value?: LoginSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
    };
}

