/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginRequestSchema
 */
export interface LoginRequestSchema {
    /**
     * 
     * @type {string}
     * @memberof LoginRequestSchema
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof LoginRequestSchema
     */
    password: string;
}

/**
 * Check if a given object implements the LoginRequestSchema interface.
 */
export function instanceOfLoginRequestSchema(value: object): value is LoginRequestSchema {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginRequestSchemaFromJSON(json: any): LoginRequestSchema {
    return LoginRequestSchemaFromJSONTyped(json, false);
}

export function LoginRequestSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginRequestSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function LoginRequestSchemaToJSON(value?: LoginRequestSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

