/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MemberSchema
 */
export interface MemberSchema {
  /**
   *
   * @type {number}
   * @memberof MemberSchema
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof MemberSchema
   */
  username: string | null;
  /**
   *
   * @type {string}
   * @memberof MemberSchema
   */
  nickname: string | null;
  /**
   *
   * @type {string}
   * @memberof MemberSchema
   */
  boj_id: string | null;
  /**
   *
   * @type {boolean}
   * @memberof MemberSchema
   */
  is_active: boolean;
  /**
   *
   * @type {boolean}
   * @memberof MemberSchema
   */
  is_off: boolean;
  /**
   *
   * @type {boolean}
   * @memberof MemberSchema
   */
  is_admin: boolean;
  /**
   *
   * @type {Date}
   * @memberof MemberSchema
   */
  created_at: Date | string;
  /**
   *
   * @type {Date}
   * @memberof MemberSchema
   */
  updated_at: Date | string;
  /**
   *
   * @type {Date}
   * @memberof MemberSchema
   */
  deleted_at: Date | null;
}

/**
 * Check if a given object implements the MemberSchema interface.
 */
export function instanceOfMemberSchema(value: object): value is MemberSchema {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('nickname' in value) || value['nickname'] === undefined) return false;
  if (!('boj_id' in value) || value['boj_id'] === undefined) return false;
  if (!('is_active' in value) || value['is_active'] === undefined) return false;
  if (!('is_off' in value) || value['is_off'] === undefined) return false;
  if (!('is_admin' in value) || value['is_admin'] === undefined) return false;
  if (!('created_at' in value) || value['created_at'] === undefined) return false;
  if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
  if (!('deleted_at' in value) || value['deleted_at'] === undefined) return false;
  return true;
}

export function MemberSchemaFromJSON(json: any): MemberSchema {
  return MemberSchemaFromJSONTyped(json, false);
}

export function MemberSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberSchema {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    username: json['username'],
    nickname: json['nickname'],
    boj_id: json['boj_id'],
    is_active: json['is_active'],
    is_off: json['is_off'],
    is_admin: json['is_admin'],
    created_at: new Date(json['created_at']),
    updated_at: new Date(json['updated_at']),
    deleted_at: json['deleted_at'] == null ? null : new Date(json['deleted_at']),
  };
}

export function MemberSchemaToJSON(value?: MemberSchema | null): any {}
