/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PenaltyQuerySchema
 */
export interface PenaltyQuerySchema {
    /**
     * 
     * @type {boolean}
     * @memberof PenaltyQuerySchema
     */
    member_is_active?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PenaltyQuerySchema
     */
    member_is_off?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof PenaltyQuerySchema
     */
    member_id?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof PenaltyQuerySchema
     */
    start_date?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PenaltyQuerySchema
     */
    end_date?: Date | null;
}

/**
 * Check if a given object implements the PenaltyQuerySchema interface.
 */
export function instanceOfPenaltyQuerySchema(value: object): value is PenaltyQuerySchema {
    return true;
}

export function PenaltyQuerySchemaFromJSON(json: any): PenaltyQuerySchema {
    return PenaltyQuerySchemaFromJSONTyped(json, false);
}

export function PenaltyQuerySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PenaltyQuerySchema {
    if (json == null) {
        return json;
    }
    return {
        
        'member_is_active': json['member_is_active'] == null ? undefined : json['member_is_active'],
        'member_is_off': json['member_is_off'] == null ? undefined : json['member_is_off'],
        'member_id': json['member_id'] == null ? undefined : json['member_id'],
        'start_date': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'end_date': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
    };
}

export function PenaltyQuerySchemaToJSON(value?: PenaltyQuerySchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'member_is_active': value['member_is_active'],
        'member_is_off': value['member_is_off'],
        'member_id': value['member_id'],
        'start_date': value['start_date'] == null ? undefined : ((value['start_date'] as any).toISOString().substring(0,10)),
        'end_date': value['end_date'] == null ? undefined : ((value['end_date'] as any).toISOString().substring(0,10)),
    };
}

