/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SolutionSchema } from './SolutionSchema';
import { SolutionSchemaFromJSON, SolutionSchemaFromJSONTyped, SolutionSchemaToJSON } from './SolutionSchema';
import type { Amount } from './Amount';
import { AmountFromJSON, AmountFromJSONTyped, AmountToJSON } from './Amount';
import type { CouponSchema } from './CouponSchema';
import { CouponSchemaFromJSON, CouponSchemaFromJSONTyped, CouponSchemaToJSON } from './CouponSchema';
import type { MemberSchema } from './MemberSchema';
import { MemberSchemaFromJSON, MemberSchemaFromJSONTyped, MemberSchemaToJSON } from './MemberSchema';

/**
 *
 * @export
 * @interface PenaltySchema
 */
export interface PenaltySchema {
  /**
   *
   * @type {number}
   * @memberof PenaltySchema
   */
  id: number;
  /**
   *
   * @type {Date}
   * @memberof PenaltySchema
   */
  day: Date | string;
  /**
   *
   * @type {Amount}
   * @memberof PenaltySchema
   */
  amount: Amount;
  /**
   *
   * @type {boolean}
   * @memberof PenaltySchema
   */
  is_penalty: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PenaltySchema
   */
  manually_edited: boolean;
  /**
   *
   * @type {MemberSchema}
   * @memberof PenaltySchema
   */
  member: MemberSchema;
  /**
   *
   * @type {Array<SolutionSchema>}
   * @memberof PenaltySchema
   */
  admitted_solutions: Array<SolutionSchema>;
  /**
   *
   * @type {Array<SolutionSchema>}
   * @memberof PenaltySchema
   */
  not_admitted_solutions: Array<SolutionSchema>;
  /**
   *
   * @type {Array<CouponSchema>}
   * @memberof PenaltySchema
   */
  coupons: Array<CouponSchema>;
}
