/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProblemStarRequestSchema
 */
export interface ProblemStarRequestSchema {
    /**
     * 
     * @type {number}
     * @memberof ProblemStarRequestSchema
     */
    problem_id: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProblemStarRequestSchema
     */
    star: boolean;
}

/**
 * Check if a given object implements the ProblemStarRequestSchema interface.
 */
export function instanceOfProblemStarRequestSchema(value: object): value is ProblemStarRequestSchema {
    if (!('problem_id' in value) || value['problem_id'] === undefined) return false;
    if (!('star' in value) || value['star'] === undefined) return false;
    return true;
}

export function ProblemStarRequestSchemaFromJSON(json: any): ProblemStarRequestSchema {
    return ProblemStarRequestSchemaFromJSONTyped(json, false);
}

export function ProblemStarRequestSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemStarRequestSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'problem_id': json['problem_id'],
        'star': json['star'],
    };
}

export function ProblemStarRequestSchemaToJSON(value?: ProblemStarRequestSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'problem_id': value['problem_id'],
        'star': value['star'],
    };
}

