/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProblemOrderingEnum = {
    Id: 'id',
    Id2: '-id',
    Stars: 'stars',
    Stars2: '-stars',
    Solutions: 'solutions',
    Solutions2: '-solutions'
} as const;
export type ProblemOrderingEnum = typeof ProblemOrderingEnum[keyof typeof ProblemOrderingEnum];


export function instanceOfProblemOrderingEnum(value: any): boolean {
    for (const key in ProblemOrderingEnum) {
        if (Object.prototype.hasOwnProperty.call(ProblemOrderingEnum, key)) {
            if (ProblemOrderingEnum[key as keyof typeof ProblemOrderingEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProblemOrderingEnumFromJSON(json: any): ProblemOrderingEnum {
    return ProblemOrderingEnumFromJSONTyped(json, false);
}

export function ProblemOrderingEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemOrderingEnum {
    return json as ProblemOrderingEnum;
}

export function ProblemOrderingEnumToJSON(value?: ProblemOrderingEnum | null): any {
    return value as any;
}

