/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProblemTagSchema
 */
export interface ProblemTagSchema {
    /**
     * 
     * @type {number}
     * @memberof ProblemTagSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProblemTagSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProblemTagSchema
     */
    boj_tag_id: string | null;
}

/**
 * Check if a given object implements the ProblemTagSchema interface.
 */
export function instanceOfProblemTagSchema(value: object): value is ProblemTagSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('boj_tag_id' in value) || value['boj_tag_id'] === undefined) return false;
    return true;
}

export function ProblemTagSchemaFromJSON(json: any): ProblemTagSchema {
    return ProblemTagSchemaFromJSONTyped(json, false);
}

export function ProblemTagSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemTagSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'boj_tag_id': json['boj_tag_id'],
    };
}

export function ProblemTagSchemaToJSON(value?: ProblemTagSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'boj_tag_id': value['boj_tag_id'],
    };
}

