/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupRequestSchema
 */
export interface SignupRequestSchema {
    /**
     * 
     * @type {string}
     * @memberof SignupRequestSchema
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequestSchema
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequestSchema
     */
    nickname: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequestSchema
     */
    boj_id: string;
}

/**
 * Check if a given object implements the SignupRequestSchema interface.
 */
export function instanceOfSignupRequestSchema(value: object): value is SignupRequestSchema {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('boj_id' in value) || value['boj_id'] === undefined) return false;
    return true;
}

export function SignupRequestSchemaFromJSON(json: any): SignupRequestSchema {
    return SignupRequestSchemaFromJSONTyped(json, false);
}

export function SignupRequestSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupRequestSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'nickname': json['nickname'],
        'boj_id': json['boj_id'],
    };
}

export function SignupRequestSchemaToJSON(value?: SignupRequestSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
        'password': value['password'],
        'nickname': value['nickname'],
        'boj_id': value['boj_id'],
    };
}

