/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SolutionOrderingEnum = {
    Id: 'id',
    Id2: '-id',
    SourceLang: 'source_lang',
    SourceLang2: '-source_lang',
    SubmittedAt: 'submitted_at',
    SubmittedAt2: '-submitted_at'
} as const;
export type SolutionOrderingEnum = typeof SolutionOrderingEnum[keyof typeof SolutionOrderingEnum];


export function instanceOfSolutionOrderingEnum(value: any): boolean {
    for (const key in SolutionOrderingEnum) {
        if (Object.prototype.hasOwnProperty.call(SolutionOrderingEnum, key)) {
            if (SolutionOrderingEnum[key as keyof typeof SolutionOrderingEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SolutionOrderingEnumFromJSON(json: any): SolutionOrderingEnum {
    return SolutionOrderingEnumFromJSONTyped(json, false);
}

export function SolutionOrderingEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolutionOrderingEnum {
    return json as SolutionOrderingEnum;
}

export function SolutionOrderingEnumToJSON(value?: SolutionOrderingEnum | null): any {
    return value as any;
}

