/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateSolutionSchema
 */
export interface UpdateSolutionSchema {
  /**
   *
   * @type {string}
   * @memberof UpdateSolutionSchema
   */
  comment?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateSolutionSchema
   */
  source_code?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateSolutionSchema
   */
  source_lang?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof UpdateSolutionSchema
   */
  is_correct_answer?: boolean | null;
  /**
   *
   * @type {Date}
   * @memberof UpdateSolutionSchema
   */
  submitted_at?: Date | null | string;
  /**
   *
   * @type {boolean}
   * @memberof UpdateSolutionSchema
   */
  star?: boolean;
}

/**
 * Check if a given object implements the UpdateSolutionSchema interface.
 */
export function instanceOfUpdateSolutionSchema(value: object): value is UpdateSolutionSchema {
  return true;
}

export function UpdateSolutionSchemaFromJSON(json: any): UpdateSolutionSchema {
  return UpdateSolutionSchemaFromJSONTyped(json, false);
}

export function UpdateSolutionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSolutionSchema {
  if (json == null) {
    return json;
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    source_code: json['source_code'] == null ? undefined : json['source_code'],
    source_lang: json['source_lang'] == null ? undefined : json['source_lang'],
    is_correct_answer: json['is_correct_answer'] == null ? undefined : json['is_correct_answer'],
    submitted_at: json['submitted_at'] == null ? undefined : new Date(json['submitted_at']),
    star: json['star'] == null ? undefined : json['star'],
  };
}

export function UpdateSolutionSchemaToJSON(value?: UpdateSolutionSchema | null): any {
  if (value == null) {
    return value;
  }
  return {
    comment: value['comment'],
    source_code: value['source_code'],
    source_lang: value['source_lang'],
    is_correct_answer: value['is_correct_answer'],
    submitted_at: value['submitted_at'] == null ? undefined : (value['submitted_at'] as any).toISOString().substring(0, 10),
    star: value['star'],
  };
}
