/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateMemberSchema
 */
export interface UserUpdateMemberSchema {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateMemberSchema
     */
    original_password: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateMemberSchema
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateMemberSchema
     */
    boj_id?: string | null;
}

/**
 * Check if a given object implements the UserUpdateMemberSchema interface.
 */
export function instanceOfUserUpdateMemberSchema(value: object): value is UserUpdateMemberSchema {
    if (!('original_password' in value) || value['original_password'] === undefined) return false;
    return true;
}

export function UserUpdateMemberSchemaFromJSON(json: any): UserUpdateMemberSchema {
    return UserUpdateMemberSchemaFromJSONTyped(json, false);
}

export function UserUpdateMemberSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateMemberSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'original_password': json['original_password'],
        'password': json['password'] == null ? undefined : json['password'],
        'boj_id': json['boj_id'] == null ? undefined : json['boj_id'],
    };
}

export function UserUpdateMemberSchemaToJSON(value?: UserUpdateMemberSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'original_password': value['original_password'],
        'password': value['password'],
        'boj_id': value['boj_id'],
    };
}

