/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CouponSchema, ErrorSchema, UseCouponRequestSchema } from '../models/index';
import {
  CouponSchemaFromJSON,
  CouponSchemaToJSON,
  ErrorSchemaFromJSON,
  ErrorSchemaToJSON,
  UseCouponRequestSchemaFromJSON,
  UseCouponRequestSchemaToJSON,
} from '../models/index';

export interface PsNoteServerAppsCoreViewsV2CouponGetRequest {
  day?: Date | null | string;
  member_id?: number | null;
  usable?: boolean | null;
}

export interface PsNoteServerAppsCoreViewsV2CouponUseCouponRequest {
  UseCouponRequestSchema: UseCouponRequestSchema;
}

/**
 *
 */
export class CouponApi extends runtime.BaseAPI {
  /**
   * 쿠폰 목록 조회
   */
  async psNoteServerAppsCoreViewsV2CouponGetRaw(
    requestParameters: PsNoteServerAppsCoreViewsV2CouponGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<CouponSchema>>> {
    const queryParameters: any = {};

    if (requestParameters['day'] != null) {
      queryParameters['day'] = (requestParameters['day'] as any).toISOString().substring(0, 10);
    }

    if (requestParameters['member_id'] != null) {
      queryParameters['member_id'] = requestParameters['member_id'];
    }

    if (requestParameters['usable'] != null) {
      queryParameters['usable'] = requestParameters['usable'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/v2/coupons`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CouponSchemaFromJSON));
  }

  /**
   * 쿠폰 목록 조회
   */
  async psNoteServerAppsCoreViewsV2CouponGet(
    requestParameters: PsNoteServerAppsCoreViewsV2CouponGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<CouponSchema>> {
    const response = await this.psNoteServerAppsCoreViewsV2CouponGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * 쿠폰 사용
   */
  async psNoteServerAppsCoreViewsV2CouponUseCouponRaw(
    requestParameters: PsNoteServerAppsCoreViewsV2CouponUseCouponRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['UseCouponRequestSchema'] == null) {
      throw new runtime.RequiredError(
        'UseCouponRequestSchema',
        'Required parameter "UseCouponRequestSchema" was null or undefined when calling psNoteServerAppsCoreViewsV2CouponUseCoupon().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/v2/coupons/use`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: UseCouponRequestSchemaToJSON(requestParameters['UseCouponRequestSchema']),
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * 쿠폰 사용
   */
  async psNoteServerAppsCoreViewsV2CouponUseCoupon(
    requestParameters: PsNoteServerAppsCoreViewsV2CouponUseCouponRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.psNoteServerAppsCoreViewsV2CouponUseCouponRaw(requestParameters, initOverrides);
  }
}
