/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface PsNoteServerAppsCoreViewsV2PenaltyGetRequest {
  member_is_active?: boolean | null;
  member_is_off?: boolean | null;
  member_id?: number | null;
  start_date?: Date | null | string;
  end_date?: Date | null | string;
}
