/* tslint:disable */
/* eslint-disable */
/**
 * PS Note API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ErrorSchema, ProblemStarRequestSchema } from '../models/index';
import { ErrorSchemaFromJSON, ErrorSchemaToJSON, ProblemStarRequestSchemaFromJSON, ProblemStarRequestSchemaToJSON } from '../models/index';

export interface PsNoteServerAppsCoreViewsV2ProblemStarPostRequest {
  ProblemStarRequestSchema: ProblemStarRequestSchema;
}

/**
 *
 */
export class ProblemStarApi extends runtime.BaseAPI {
  /**
   * 문제 별표 표시
   */
  async psNoteServerAppsCoreViewsV2ProblemStarPostRaw(
    requestParameters: PsNoteServerAppsCoreViewsV2ProblemStarPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['ProblemStarRequestSchema'] == null) {
      throw new runtime.RequiredError(
        'ProblemStarRequestSchema',
        'Required parameter "ProblemStarRequestSchema" was null or undefined when calling psNoteServerAppsCoreViewsV2ProblemStarPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/v2/problem-stars`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ProblemStarRequestSchemaToJSON(requestParameters['ProblemStarRequestSchema']),
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * 문제 별표 표시
   */
  async psNoteServerAppsCoreViewsV2ProblemStarPost(
    requestParameters: PsNoteServerAppsCoreViewsV2ProblemStarPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.psNoteServerAppsCoreViewsV2ProblemStarPostRaw(requestParameters, initOverrides);
  }
}
