export const PROBLEMS = [
  {
    id: 935,
    name: '다리 놓기',
    boj_id: '1010',
    level: 'silver_5',
    created_at: '2024-08-25T07:28:37.237916',
    updated_at: '2024-08-25T07:28:37.237992',
    is_solved: false,
    is_starred: false,
    stars: 0,
    tags: [
      {
        id: 7,
        name: '수학',
        boj_tag_id: '124',
      },
      {
        id: 19,
        name: '다이나믹 프로그래밍',
        boj_tag_id: '25',
      },
      {
        id: 31,
        name: '조합론',
        boj_tag_id: '6',
      },
    ],
    label: '1010 다리 놓기',
    url: 'https://ps-note-client.kodori.dev/problem/935',
    solutions: 3,
  },
];

export const SOLUTIONS = [
  {
    id: 87,
    member: {
      id: 7,
      username: null,
      nickname: '박정주',
      boj_id: 'wnwjdqkr',
      is_active: true,
      created_at: '2024-08-23T19:02:35.203823',
      updated_at: '2024-08-24T08:27:25.146301',
      deleted_at: null,
    },
    problem: {
      id: 68,
      name: '방 번호',
      boj_id: '1475',
      level: 'silver_5',
      created_at: '2024-08-23T19:03:34.870390',
      updated_at: '2024-08-23T19:03:34.870424',
      is_solved: false,
      is_starred: false,
      stars: 0,
      tags: [
        {
          id: 15,
          name: '구현',
          boj_tag_id: '102',
        },
      ],
      label: '1475 방 번호',
      url: 'https://ps-note-client.kodori.dev/problem/68',
      solutions: 6,
    },
    comment: '## 아이디어\n\n💡 \n\n## 코멘트\n\n',
    source_lang: 'c++',
    source_code:
      "#include <iostream>\n#include <vector>\n#include <string>\n#include <algorithm>\nusing namespace std;\n\n\nint main()\n{\n\tios::sync_with_stdio(0); cin.tie(0); cout.tie(0);\n\n\tint n;\n\tcin >> n;\n\tint number[10] = {};\n\twhile (0 < n)\n\t{\n\t\tnumber[n % 10]++;\n\t\tn /= 10;\n\t}\n\n\tint ans = 1;\n\tfor (int i = 0; i < 10; i++)\n\t{\n\t\tif (i == 6 || i == 9) continue;\n\t\tans = max(ans, number[i]);\n\t}\n\n\tans = max(ans, (number[6] + number[9] + 1) / 2);\n\tcout << ans << '\\n';\n\n\treturn 0;\n}",
    is_correct_answer: true,
    submitted_at: '2024-05-10',
    imported_from_notion: true,
    is_fully_parsed: true,
    notion_page_id: '34add2d2-1281-450c-98aa-87f2e210996c',
    is_boj_verified: true,
    boj_solution_id: '78155718',
    created_at: '2024-08-23T19:03:35.486577',
    updated_at: '2024-08-23T19:03:35.486612',
    deleted_at: null,
    status_label: '',
    score_label: 'AC',
  },
  {
    id: 154,
    member: {
      id: 8,
      username: null,
      nickname: '이소영',
      boj_id: 'so0o2',
      is_active: true,
      created_at: '2024-08-23T19:04:36.071431',
      updated_at: '2024-08-23T19:15:54.681564',
      deleted_at: null,
    },
    problem: {
      id: 68,
      name: '방 번호',
      boj_id: '1475',
      level: 'silver_5',
      created_at: '2024-08-23T19:03:34.870390',
      updated_at: '2024-08-23T19:03:34.870424',
      is_solved: false,
      is_starred: false,
      stars: 0,
      tags: [
        {
          id: 15,
          name: '구현',
          boj_tag_id: '102',
        },
      ],
      label: '1475 방 번호',
      url: 'https://ps-note-client.kodori.dev/problem/68',
      solutions: 6,
    },
    comment:
      '## 아이디어\n\n💡 생각을 하고 코드를 쓰기 시작한다\n\n## 코멘트\n\ncnt를 마지막에 더해줬었다\n\n이렇게 멍청한 사람이 사회로 나가도 되는걸까?\n\n',
    source_lang: 'python',
    source_code:
      'arr=list(input())\narr2=[0]*10\nfor i in arr:\n    arr2[int(i)]+=1\n\ncnt=min(arr2[6],arr2[9])\narr2[6]-=cnt\narr2[9]-=cnt\nprint(*arr2)\narr2[6]=(arr2[6]+arr2[9])//2+(arr2[6]+arr2[9])%2+cnt\narr2[9]=0\n\nprint(max(arr2))\nprint(cnt)\n',
    is_correct_answer: true,
    submitted_at: '2024-05-29',
    imported_from_notion: true,
    is_fully_parsed: false,
    notion_page_id: '68bf2f58-f07e-417a-9655-bd78bc2e34f8',
    is_boj_verified: true,
    boj_solution_id: '78980643',
    created_at: '2024-08-23T19:05:34.590855',
    updated_at: '2024-08-23T19:05:34.590909',
    deleted_at: null,
    status_label: '',
    score_label: 'AC',
  },
  {
    id: 180,
    member: {
      id: 6,
      username: null,
      nickname: '한석기',
      boj_id: 'hski0939',
      is_active: true,
      created_at: '2024-08-23T19:01:20.265271',
      updated_at: '2024-08-23T19:15:02.935540',
      deleted_at: null,
    },
    problem: {
      id: 68,
      name: '방 번호',
      boj_id: '1475',
      level: 'silver_5',
      created_at: '2024-08-23T19:03:34.870390',
      updated_at: '2024-08-23T19:03:34.870424',
      is_solved: false,
      is_starred: false,
      stars: 0,
      tags: [
        {
          id: 15,
          name: '구현',
          boj_tag_id: '102',
        },
      ],
      label: '1475 방 번호',
      url: 'https://ps-note-client.kodori.dev/problem/68',
      solutions: 6,
    },
    comment: '## 아이디어\n\n💡 구현 잘 하면 됨\n\n## 코멘트\n\n',
    source_lang: 'c++',
    source_code:
      "#include <iostream>\n#include <queue>\n#include <vector>\n#include <algorithm>\n#include <string>\n#include <stack>\n#include <iterator>\n#include <cmath>\n#define ll long long\nusing namespace std;\nint N;\nint arr[10];\nint ans;\nint main()\n{\n    ios_base::sync_with_stdio(false);\n    cin.tie(nullptr);\n    cout.tie(nullptr);\n    string str;\n    cin >> str;\n    for (int i = 0; i < str.size(); i++) {\n        arr[str[i] - '0']++;\n    }\n    arr[6] += arr[9];\n    if (arr[6] % 2) arr[6] = arr[6] / 2 + 1;\n    else arr[6] /= 2;\n    for (int i = 0; i < 9; i++) {\n        ans = max(arr[i], ans);\n    }\n    cout << ans << '\\n';\n    return 0;\n}\n\n",
    is_correct_answer: true,
    submitted_at: '2024-06-05',
    imported_from_notion: true,
    is_fully_parsed: true,
    notion_page_id: 'f7ecc63e-0f92-4bf2-af9d-e23ffea0709a',
    is_boj_verified: true,
    boj_solution_id: '79276310',
    created_at: '2024-08-23T19:06:17.251424',
    updated_at: '2024-08-23T19:06:17.251455',
    deleted_at: null,
    status_label: '',
    score_label: 'AC',
  },
  {
    id: 386,
    member: {
      id: 14,
      username: null,
      nickname: '정은교',
      boj_id: 'hithere1003',
      is_active: true,
      created_at: '2024-08-23T19:11:02.964605',
      updated_at: '2024-08-24T08:27:29.880367',
      deleted_at: null,
    },
    problem: {
      id: 68,
      name: '방 번호',
      boj_id: '1475',
      level: 'silver_5',
      created_at: '2024-08-23T19:03:34.870390',
      updated_at: '2024-08-23T19:03:34.870424',
      is_solved: false,
      is_starred: false,
      stars: 0,
      tags: [
        {
          id: 15,
          name: '구현',
          boj_tag_id: '102',
        },
      ],
      label: '1475 방 번호',
      url: 'https://ps-note-client.kodori.dev/problem/68',
      solutions: 6,
    },
    comment: '## 아이디어\n\n💡 \n\n## 코멘트\n\n',
    source_lang: 'c++',
    source_code: '',
    is_correct_answer: true,
    submitted_at: '2024-07-24',
    imported_from_notion: true,
    is_fully_parsed: true,
    notion_page_id: '0b9f6348-d06e-4993-b827-cffb7666d318',
    is_boj_verified: false,
    boj_solution_id: null,
    created_at: '2024-08-23T19:12:22.182567',
    updated_at: '2024-08-23T19:12:22.182606',
    deleted_at: null,
    status_label: '백준 연동 실패',
    score_label: 'AC',
  },
  {
    id: 398,
    member: {
      id: 10,
      username: null,
      nickname: '정서영',
      boj_id: 'diyung',
      is_active: true,
      created_at: '2024-08-23T19:09:32.452441',
      updated_at: '2024-08-24T08:27:30.203099',
      deleted_at: null,
    },
    problem: {
      id: 68,
      name: '방 번호',
      boj_id: '1475',
      level: 'silver_5',
      created_at: '2024-08-23T19:03:34.870390',
      updated_at: '2024-08-23T19:03:34.870424',
      is_solved: false,
      is_starred: false,
      stars: 0,
      tags: [
        {
          id: 15,
          name: '구현',
          boj_tag_id: '102',
        },
      ],
      label: '1475 방 번호',
      url: 'https://ps-note-client.kodori.dev/problem/68',
      solutions: 6,
    },
    comment: '## 아이디어\n\n💡 \n\n## 코멘트\n\n',
    source_lang: 'c++',
    source_code:
      "#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n\tios::sync_with_stdio(0); cin.tie(0); cout.tie(0);\n\n\tstring n;\n\tcin >> n;\n\t\n\tint count[10] = {0, };\n\tfor(char c : n) count[c-'0']++;\n\tcount[6] = count[9] = (count[6]+count[9]+1)/2;\n\n\tint max_count = *max_element(count, count+10);\n\tcout << max_count;\n}",
    is_correct_answer: true,
    submitted_at: '2024-07-25',
    imported_from_notion: true,
    is_fully_parsed: true,
    notion_page_id: 'bbd65689-211a-450d-b55b-c1c8528cbd0c',
    is_boj_verified: true,
    boj_solution_id: '81598454',
    created_at: '2024-08-23T19:12:36.383859',
    updated_at: '2024-08-23T19:12:36.383894',
    deleted_at: null,
    status_label: '',
    score_label: 'AC',
  },
  {
    id: 402,
    member: {
      id: 14,
      username: null,
      nickname: '정은교',
      boj_id: 'hithere1003',
      is_active: true,
      created_at: '2024-08-23T19:11:02.964605',
      updated_at: '2024-08-24T08:27:29.880367',
      deleted_at: null,
    },
    problem: {
      id: 68,
      name: '방 번호',
      boj_id: '1475',
      level: 'silver_5',
      created_at: '2024-08-23T19:03:34.870390',
      updated_at: '2024-08-23T19:03:34.870424',
      is_solved: false,
      is_starred: false,
      stars: 0,
      tags: [
        {
          id: 15,
          name: '구현',
          boj_tag_id: '102',
        },
      ],
      label: '1475 방 번호',
      url: 'https://ps-note-client.kodori.dev/problem/68',
      solutions: 6,
    },
    comment: '## 아이디어\n\n💡 6이랑 9가 방번호에 포함될때 count를 유의한다.\n\n## 코멘트\n\n',
    source_lang: 'c++',
    source_code:
      '#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <cmath>\nusing namespace std;\n\nint main() {\n    ios_base::sync_with_stdio(0);\n    cin.tie(0); cout.tie(0);\n\n    int N;\n    cin >> N;\n\n    int arr[10] = {0};\n\n    while (N > 0) {\n        int r = N % 10;\n        arr[r]++;\n        N /= 10;\n    }\n\n    int cnt = arr[6] + arr[9];\n    arr[6] = arr[9] = (cnt + 1) / 2;\n\n    int maxCnt = *max_element(arr, arr + 10);\n\n    cout << maxCnt << "\\n";\n\n    return 0;\n}',
    is_correct_answer: true,
    submitted_at: '2024-07-25',
    imported_from_notion: true,
    is_fully_parsed: true,
    notion_page_id: 'c4b5b25b-9960-4499-9854-9122236b293a',
    is_boj_verified: false,
    boj_solution_id: null,
    created_at: '2024-08-23T19:12:36.490573',
    updated_at: '2024-08-23T19:12:36.490607',
    deleted_at: null,
    status_label: '백준 연동 실패',
    score_label: 'AC',
  },
];

export const TODAY_PENALTY = [
  {
    day: '2024-08-27',
    member: {
      id: 1,
      username: null,
      nickname: '이하윤',
      boj_id: 'lhy100494',
      is_active: true,
      created_at: '2024-08-23T19:01:01.116581',
      updated_at: '2024-08-23T19:15:38.885390',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 1820,
        member: {
          id: 1,
          username: null,
          nickname: '이하윤',
          boj_id: 'lhy100494',
          is_active: true,
          created_at: '2024-08-23T19:01:01.116581',
          updated_at: '2024-08-23T19:15:38.885390',
          deleted_at: null,
        },
        problem: {
          id: 1520,
          name: '무한부스터',
          boj_id: '17391',
          level: 'silver_1',
          created_at: '2024-08-28T06:00:30.369705',
          updated_at: '2024-08-28T06:00:30.369759',
          is_solved: false,
          is_starred: false,
          stars: 0,
          tags: [
            {
              id: 3,
              name: '그래프 이론',
              boj_tag_id: '7',
            },
            {
              id: 9,
              name: '너비 우선 탐색',
              boj_tag_id: '126',
            },
            {
              id: 11,
              name: '그래프 탐색',
              boj_tag_id: '11',
            },
            {
              id: 19,
              name: '다이나믹 프로그래밍',
              boj_tag_id: '25',
            },
          ],
          label: '17391 무한부스터',
          url: 'https://ps-note-client.kodori.dev/problem/1520',
          solutions: 1,
        },
        comment: '## 아이디어\n\n💡 간단 2차원 bfs\n\n## 코멘트\n\n',
        source_lang: 'c++',
        source_code:
          '#include <stdio.h>\n#include <iostream>\n#include <stdlib.h>\n#include <string.h>\n#include <string>\n#include <algorithm>\n#include <set>\n#include <vector>\n#include <stack>\n#include <queue>\n#include <math.h>\n#include <tuple>\n#include <map>\n#include <bitset>\n#include <functional>\n#include <cstring>\n#include <unordered_set>\nusing namespace std;\n#define ll long long\n#define llinf 2e18\n#define intinf 2147183647\n\nll n, m;\nvector<vector<ll>> visited(301, vector<ll>(301, llinf));\nvector<vector<ll>> arr(301, vector<ll>(301));\nqueue<pair<pair<ll,ll>,ll>> q;\nvoid bfs() {\n\twhile (!q.empty()) {\n\t\tll x = q.front().first.first, y = q.front().first.second;\n\t\tll c = q.front().second;\n\t\tq.pop();\n\n\t\t//cout << x << " " << y << " " << c << "\\n";\n\t\tif (c >= visited[x][y])continue;\n\t\tvisited[x][y] = c;\n\n\t\tfor (ll i = 1; i <= arr[x][y]; i++) {\n\t\t\tif (x + i < n && visited[x+i][y]>c)q.push({{x + i,y},c + 1});\n\t\t\tif (y + i < m && visited[x][y+i]>c)q.push({{x,y + i},c + 1});\n\t\t}\n\t}\n\n}\nint main(void) {\n\tios::sync_with_stdio(false);\n\tcin.tie(NULL);\n\tcout.tie(NULL);\n\n\tcin >> n >> m;\n\tfor (ll i = 0; i < n; i++) {\n\t\tfor (ll j = 0; j < m; j++) {\n\t\t\tcin >> arr[i][j];\n\t\t}\n\t}\n\tq.push({ {0,0},0 });\n\tbfs();\n\n\tcout << visited[n - 1][m - 1];\n}\n',
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: true,
        is_fully_parsed: true,
        notion_page_id: '27c80632-44d8-4299-b0ee-cdcf4fdf05b1',
        is_boj_verified: true,
        boj_solution_id: '83076095',
        created_at: '2024-08-28T06:00:30.466282',
        updated_at: '2024-08-28T06:00:30.466326',
        deleted_at: null,
        status_label: '',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 3,
      username: null,
      nickname: '박준우',
      boj_id: 'junu22',
      is_active: true,
      created_at: '2024-08-23T19:01:01.194443',
      updated_at: '2024-08-24T08:27:07.565711',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 1815,
        member: {
          id: 3,
          username: null,
          nickname: '박준우',
          boj_id: 'junu22',
          is_active: true,
          created_at: '2024-08-23T19:01:01.194443',
          updated_at: '2024-08-24T08:27:07.565711',
          deleted_at: null,
        },
        problem: {
          id: 339,
          name: '연결 요소의 개수',
          boj_id: '11724',
          level: 'silver_2',
          created_at: '2024-08-23T19:16:31.716721',
          updated_at: '2024-08-23T19:16:31.716757',
          is_solved: false,
          is_starred: false,
          stars: 0,
          tags: [
            {
              id: 3,
              name: '그래프 이론',
              boj_tag_id: '7',
            },
            {
              id: 9,
              name: '너비 우선 탐색',
              boj_tag_id: '126',
            },
            {
              id: 11,
              name: '그래프 탐색',
              boj_tag_id: '11',
            },
            {
              id: 30,
              name: '깊이 우선 탐색',
              boj_tag_id: '127',
            },
          ],
          label: '11724 연결 요소의 개수',
          url: 'https://ps-note-client.kodori.dev/problem/339',
          solutions: 3,
        },
        comment:
          '## 아이디어\n\n💡 연결되어있는 것들을 하나의 그룹으로 묶을 때, 몇개의 그룹으로 나뉘는지 보면 된다\n그게 연결요소의 개수라고 한다네요\n\n## 코멘트\n\n',
        source_lang: 'c++',
        source_code:
          "#include <bits/stdc++.h>\n#define endl '\\n'\n#define ALL(x) x.begin(), x.end()\n#define fastio cin.tie(0)->sync_with_stdio(0)\n#define rnprc cout << setprecision(12)\n// #define TC\n\nusing namespace std;\n\ntypedef long long ll;\ntypedef pair<ll, ll> pll;\n\nconst ll mod = 1'000'000'007;\n\nll gcd(ll a, ll b) { return b ? gcd(b, a % b) : a; }\n\nstruct Vertex\n{\n  bool visited;\n  vector<int> adj;\n} Vertex[1010];\n\nvoid dfs(int curr)\n{\n  if (Vertex[curr].visited)\n    return;\n\n  Vertex[curr].visited = true;\n\n  for (auto x : Vertex[curr].adj)\n  {\n    dfs(x);\n  }\n}\n\nvoid solve()\n{\n  int N, M;\n  cin >> N >> M;\n\n  while (M--)\n  {\n    int u, v;\n    cin >> u >> v;\n\n    Vertex[u].adj.push_back(v);\n    Vertex[v].adj.push_back(u);\n  }\n\n  int ans = 0;\n\n  for (int i = 1; i <= N; i++)\n  {\n    if (!Vertex[i].visited)\n      ans++;\n\n    dfs(i);\n  }\n\n  cout << ans << endl;\n}\n\nint main(void)\n{\n  fastio;\n\n#ifndef ONLINE_JUDGE\n  freopen(\"input.txt\", \"r\", stdin);\n#endif\n\n  ll tc = 1;\n#ifdef TC\n  cin >> tc;\n#endif\n\n  while (tc--)\n  {\n    solve();\n  }\n\n  return 0;\n}",
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: true,
        is_fully_parsed: true,
        notion_page_id: '44a816b0-55d8-440d-b51b-7ac4365d13f7',
        is_boj_verified: true,
        boj_solution_id: '83071342',
        created_at: '2024-08-28T02:19:24.745845',
        updated_at: '2024-08-28T02:19:24.745873',
        deleted_at: null,
        status_label: '',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 4,
      username: 'tonynamy',
      nickname: '남정연',
      boj_id: 'tonynamy',
      is_active: true,
      created_at: '2024-08-23T19:01:10.296094',
      updated_at: '2024-08-23T19:28:19.052332',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [],
    not_admitted_solutions: [
      {
        id: 1810,
        member: {
          id: 4,
          username: 'tonynamy',
          nickname: '남정연',
          boj_id: 'tonynamy',
          is_active: true,
          created_at: '2024-08-23T19:01:10.296094',
          updated_at: '2024-08-23T19:28:19.052332',
          deleted_at: null,
        },
        problem: {
          id: 1504,
          name: '가톨릭대는 고양이를 사랑해',
          boj_id: '23035',
          level: 'platinum_4',
          created_at: '2024-08-28T00:51:54.559166',
          updated_at: '2024-08-28T00:51:54.559220',
          is_solved: false,
          is_starred: false,
          stars: 0,
          tags: [
            {
              id: 14,
              name: '정렬',
              boj_tag_id: '97',
            },
            {
              id: 64,
              name: '가장 긴 증가하는 부분 수열: O(n log n)',
              boj_tag_id: '43',
            },
          ],
          label: '23035 가톨릭대는 고양이를 사랑해',
          url: 'https://ps-note-client.kodori.dev/problem/1504',
          solutions: 1,
        },
        comment:
          '## 아이디어\n<!-- AC의 경우에는 간단한 아이디어를,\nWA의 경우에는 문제 풀이를 상세히 기록해 주세요.\n(주석은 삭제 후 코멘트를 작성해 주세요.) -->\n\n사실 안풀었지롱~~\n\n\n### 사실 안풀었지롱~~~',
        source_lang: 'Python',
        source_code: 'print("사실 안풀었지롱")',
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: false,
        is_fully_parsed: null,
        notion_page_id: null,
        is_boj_verified: false,
        boj_solution_id: null,
        created_at: '2024-08-28T00:52:43.870082',
        updated_at: '2024-08-28T00:52:43.870128',
        deleted_at: null,
        status_label: '백준 연동 실패',
        score_label: 'AC',
      },
    ],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 5,
      username: null,
      nickname: '이동주',
      boj_id: 'dongzoolee',
      is_active: true,
      created_at: '2024-08-23T19:01:20.210910',
      updated_at: '2024-08-24T08:27:25.494124',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 1816,
        member: {
          id: 5,
          username: null,
          nickname: '이동주',
          boj_id: 'dongzoolee',
          is_active: true,
          created_at: '2024-08-23T19:01:20.210910',
          updated_at: '2024-08-24T08:27:25.494124',
          deleted_at: null,
        },
        problem: {
          id: 935,
          name: '다리 놓기',
          boj_id: '1010',
          level: 'silver_5',
          created_at: '2024-08-25T07:28:37.237916',
          updated_at: '2024-08-25T07:28:37.237992',
          is_solved: false,
          is_starred: false,
          stars: 0,
          tags: [
            {
              id: 7,
              name: '수학',
              boj_tag_id: '124',
            },
            {
              id: 19,
              name: '다이나믹 프로그래밍',
              boj_tag_id: '25',
            },
            {
              id: 31,
              name: '조합론',
              boj_tag_id: '6',
            },
          ],
          label: '1010 다리 놓기',
          url: 'https://ps-note-client.kodori.dev/problem/935',
          solutions: 3,
        },
        comment: '## 아이디어\n\n💡 \n\n## 코멘트\n\n',
        source_lang: 'c++',
        source_code:
          '#include <bits/stdc++.h>\n\nusing namespace std;\n\nint comb[31][31];\n\nvoid build_comb(int n) {\n  for (int i = 0; i <= n; i++) {\n    comb[i][0] = 1;\n    comb[i][i] = 1;\n  }\n\n  for (int i = 2; i <= n; i++) {\n    for (int j = 1; j < i; j++) {\n      comb[i][j] = comb[i - 1][j - 1] + comb[i - 1][j];\n    }\n  }\n}\n\nint main() {\n  ios::sync_with_stdio(0);\n  cin.tie(0), cout.tie(0);\n\n  build_comb(30);\n\n  int tc, a, b;\n  cin >> tc;\n\n  while (tc--) {\n    cin >> a >> b;\n    cout << comb[b][a] << "\\n";\n  }\n\n  return 0;\n}',
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: true,
        is_fully_parsed: true,
        notion_page_id: '62fdc4da-78c4-45f0-a42d-68b05010a8a5',
        is_boj_verified: true,
        boj_solution_id: '83070496',
        created_at: '2024-08-28T02:19:25.133592',
        updated_at: '2024-08-28T02:19:25.133644',
        deleted_at: null,
        status_label: '',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 6,
      username: null,
      nickname: '한석기',
      boj_id: 'hski0939',
      is_active: true,
      created_at: '2024-08-23T19:01:20.265271',
      updated_at: '2024-08-23T19:15:02.935540',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 7,
      username: null,
      nickname: '박정주',
      boj_id: 'wnwjdqkr',
      is_active: true,
      created_at: '2024-08-23T19:02:35.203823',
      updated_at: '2024-08-24T08:27:25.146301',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [],
    not_admitted_solutions: [],
    coupons: [
      {
        id: 11,
        name: '면제쿠폰',
        member: {
          id: 7,
          username: null,
          nickname: '박정주',
          boj_id: 'wnwjdqkr',
          is_active: true,
          created_at: '2024-08-23T19:02:35.203823',
          updated_at: '2024-08-24T08:27:25.146301',
          deleted_at: null,
        },
        used_at: '2024-08-27T00:00:00',
        valid_to: '2024-09-02T00:00:00',
        valid_from: '2024-08-26T00:00:00',
        created_at: '2024-08-27T02:04:20',
        updated_at: '2024-08-27T02:04:20',
      },
    ],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 8,
      username: null,
      nickname: '이소영',
      boj_id: 'so0o2',
      is_active: true,
      created_at: '2024-08-23T19:04:36.071431',
      updated_at: '2024-08-23T19:15:54.681564',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 9,
      username: null,
      nickname: '손기령',
      boj_id: 'lickelon',
      is_active: true,
      created_at: '2024-08-23T19:07:46.609014',
      updated_at: '2024-08-24T08:27:30.094142',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 1818,
        member: {
          id: 9,
          username: null,
          nickname: '손기령',
          boj_id: 'lickelon',
          is_active: true,
          created_at: '2024-08-23T19:07:46.609014',
          updated_at: '2024-08-24T08:27:30.094142',
          deleted_at: null,
        },
        problem: {
          id: 1519,
          name: '행복한 나무',
          boj_id: '13005',
          level: 'platinum_4',
          created_at: '2024-08-28T02:19:22.448101',
          updated_at: '2024-08-28T02:19:22.448146',
          is_solved: false,
          is_starred: false,
          stars: 0,
          tags: [
            {
              id: 3,
              name: '그래프 이론',
              boj_tag_id: '7',
            },
            {
              id: 11,
              name: '그래프 탐색',
              boj_tag_id: '11',
            },
            {
              id: 30,
              name: '깊이 우선 탐색',
              boj_tag_id: '127',
            },
            {
              id: 43,
              name: '트리',
              boj_tag_id: '120',
            },
          ],
          label: '13005 행복한 나무',
          url: 'https://ps-note-client.kodori.dev/problem/1519',
          solutions: 1,
        },
        comment:
          '## 아이디어\n\n💡 이 나무가 행복을 알까요..?\n\n## 코멘트\n\n행복한 나무가 되기 위해 어떤 노드를 제거해야 하는지 알아야 한다.\n\n제거해야 할 조건은 다음과 같다.\n\n1번 조건은 임의의 dist 중 최댓값만 확인해도 알 수 있다. 루트부터 경로에 존재하는 모든 노드로 가능 경로의 길이 중 최소값을 루트부터 해당 노드까지의 경로의 길이에서 빼주면 dist의 최댓값을 구할 수 있다.\n\n전체 과정을 DFS를 통해 순회하면 제거해야 할 노드를 구할 수 있다.\n\n',
        source_lang: 'c++',
        source_code:
          '#include <bits/stdc++.h>\n\n#define all(x) (x).begin(), (x).end()\n\n#define INF 0x7FFFFFFF\n\nusing namespace std;\n\nusing ll = long long;\nusing ld = long double;\nusing pii = pair<int,int>;\nusing pll = pair<ll, ll>;\n\nstruct node {\n    int idx;\n    ll m_dist;\n    ll dist;\n};\n\nint main()\n{\n    ios::sync_with_stdio(0);\n    cin.tie(0); cout.tie(0);\n\n    int n;\n    cin >> n;\n    vector<ll> num(n+1);\n    for(int i = 1; i <= n; i++) cin >> num[i];\n    vector<vector<pll>> edge(n+1);\n    for(int i = 0; i < n-1; i++) {\n        int p, c;\n        cin >> p >> c;\n        edge[p].emplace_back(i+2, c);\n    }\n    stack<node> _st;\n    _st.push({1, 0, 0});\n    vector<bool> check(n+1, false);\n    while(!_st.empty()) {\n        auto curr = _st.top(); _st.pop();\n        if(curr.dist - curr.m_dist > num[curr.idx]) {\n            check[curr.idx] = true;\n        }\n        for(auto u : edge[curr.idx]) {\n            node next;\n            next.idx = u.first;\n            next.dist = curr.dist + u.second;\n            next.m_dist = min(next.dist, curr.m_dist);\n            _st.push(next);\n            if(check[curr.idx]) check[next.idx] = true;\n        }\n    }\n    int cnt = 0;\n    for(int i = 1; i <= n; i++) {\n        if(check[i]) cnt++;\n    }\n    cout << cnt;\n\n    return 0;\n}',
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: true,
        is_fully_parsed: false,
        notion_page_id: '5ce3a4a3-751f-48a5-8b85-2ba120025533',
        is_boj_verified: true,
        boj_solution_id: '83044415',
        created_at: '2024-08-28T02:19:26.272791',
        updated_at: '2024-08-28T02:19:26.272827',
        deleted_at: null,
        status_label: '',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 10,
      username: null,
      nickname: '정서영',
      boj_id: 'diyung',
      is_active: true,
      created_at: '2024-08-23T19:09:32.452441',
      updated_at: '2024-08-24T08:27:30.203099',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 1814,
        member: {
          id: 10,
          username: null,
          nickname: '정서영',
          boj_id: 'diyung',
          is_active: true,
          created_at: '2024-08-23T19:09:32.452441',
          updated_at: '2024-08-24T08:27:30.203099',
          deleted_at: null,
        },
        problem: {
          id: 951,
          name: '헌내기는 친구가 필요해',
          boj_id: '21736',
          level: 'silver_2',
          created_at: '2024-08-25T07:30:10.331412',
          updated_at: '2024-08-25T07:30:10.331494',
          is_solved: false,
          is_starred: false,
          stars: 0,
          tags: [
            {
              id: 3,
              name: '그래프 이론',
              boj_tag_id: '7',
            },
            {
              id: 9,
              name: '너비 우선 탐색',
              boj_tag_id: '126',
            },
            {
              id: 11,
              name: '그래프 탐색',
              boj_tag_id: '11',
            },
            {
              id: 30,
              name: '깊이 우선 탐색',
              boj_tag_id: '127',
            },
          ],
          label: '21736 헌내기는 친구가 필요해',
          url: 'https://ps-note-client.kodori.dev/problem/951',
          solutions: 2,
        },
        comment: '## 아이디어\n\n💡 \n\n## 코멘트\n\n',
        source_lang: 'c++',
        source_code:
          "#include <iostream>\n#include <queue>\nusing namespace std;\n\nint n, m, ans = 0;\nchar campus[600][600];\nbool visited[600][600];\nint dx[] = {1, -1, 0, 0}, dy[] = {0, 0, 1, -1};\nqueue<pair <int, int> > q;\n\nvoid solve() {\n    while(!q.empty()) {\n        int x = q.front().first, y = q.front().second;\n        q.pop();\n        for(int i=0; i<4; i++) {\n            int nx = x + dx[i], ny = y + dy[i];\n            if(nx>=0 && nx<n && ny>=0 && ny<m && !visited[nx][ny] && campus[nx][ny] != 'X') {\n                visited[nx][ny] = true;\n                q.push({nx, ny});\n                if(campus[nx][ny] == 'P') ans++;\n            }\n        }\n    }\n}\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(0);\n\n    cin >> n >> m;\n\n    for(int i=0; i<n; i++){\n        for(int j=0; j<m; j++) {\n            cin >> campus[i][j];\n            if(campus[i][j] == 'I') {\n                q.push({i, j});\n                visited[i][j] = true;\n            }\n        }\n    }\n\n    solve();\n    \n    cout << (ans > 0 ? to_string(ans) : \"TT\");\n}\n",
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: true,
        is_fully_parsed: true,
        notion_page_id: '94e319fa-ed33-4f04-8cd7-f6fb63e349a3',
        is_boj_verified: true,
        boj_solution_id: '83072388',
        created_at: '2024-08-28T02:19:24.371431',
        updated_at: '2024-08-28T02:19:24.371469',
        deleted_at: null,
        status_label: '',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 11,
      username: null,
      nickname: '이승영',
      boj_id: 'esybd02',
      is_active: true,
      created_at: '2024-08-23T19:09:32.527529',
      updated_at: '2024-08-24T08:27:25.271312',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 1811,
        member: {
          id: 11,
          username: null,
          nickname: '이승영',
          boj_id: 'esybd02',
          is_active: true,
          created_at: '2024-08-23T19:09:32.527529',
          updated_at: '2024-08-24T08:27:25.271312',
          deleted_at: null,
        },
        problem: {
          id: 3,
          name: '케빈 베이컨의 6단계 법칙',
          boj_id: '1389',
          level: 'silver_1',
          created_at: '2024-08-23T19:01:01.069297',
          updated_at: '2024-08-23T19:01:01.069332',
          is_solved: false,
          is_starred: false,
          stars: 0,
          tags: [
            {
              id: 3,
              name: '그래프 이론',
              boj_tag_id: '7',
            },
            {
              id: 9,
              name: '너비 우선 탐색',
              boj_tag_id: '126',
            },
            {
              id: 10,
              name: '플로이드–워셜',
              boj_tag_id: '31',
            },
            {
              id: 11,
              name: '그래프 탐색',
              boj_tag_id: '11',
            },
            {
              id: 12,
              name: '최단 경로',
              boj_tag_id: '215',
            },
          ],
          label: '1389 케빈 베이컨의 6단계 법칙',
          url: 'https://ps-note-client.kodori.dev/problem/3',
          solutions: 3,
        },
        comment: '## 아이디어\n\n💡 \n\n## 코멘트\n\n',
        source_lang: 'java',
        source_code:
          'import java.io.BufferedReader;\nimport java.io.BufferedWriter;\nimport java.io.IOException;\nimport java.io.InputStreamReader;\nimport java.io.OutputStreamWriter;\nimport java.util.StringTokenizer;\n \npublic class Main {\n    static final int INF = 987654321;\n \n    public static void main(String[] args) throws NumberFormatException, IOException {\n        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n        BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(System.out));\n        StringTokenizer st = new StringTokenizer(br.readLine());\n \n        int N = Integer.parseInt(st.nextToken());\n        int M = Integer.parseInt(st.nextToken());\n        int[][] arr = new int[N + 1][N + 1];\n \n        for (int i = 1; i <= N; i++) {\n            for (int j = 1; j <= N; j++) {\n                arr[i][j] = INF;\n \n                if (i == j) {\n                    arr[i][j] = 0;\n                }\n            }\n        }\n        \n        for (int i = 0; i < M; i++) {\n            st = new StringTokenizer(br.readLine());\n            int x = Integer.parseInt(st.nextToken());\n            int y = Integer.parseInt(st.nextToken());\n \n            arr[x][y] = arr[y][x] = 1;\n        }\n \n        for (int k = 1; k <= N; k++) {\n            for (int i = 1; i <= N; i++) {\n                for (int j = 1; j <= N; j++) {\n                    if (arr[i][j] > arr[i][k] + arr[k][j]) {\n                        arr[i][j] = arr[i][k] + arr[k][j];\n                    }\n                }\n            }\n        }\n \n        int res = INF;\n        int idx = -1;\n \n        for (int i = 1; i <= N; i++) {\n            int total = 0;\n            for (int j = 1; j <= N; j++) {\n                total += arr[i][j];\n            }\n \n            if (res > total) {\n                res = total;\n                idx = i;\n            }\n        }\n \n        bw.write(idx + "\\n");\n        bw.flush();\n        bw.close();\n        br.close();\n    }\n \n}',
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: true,
        is_fully_parsed: true,
        notion_page_id: '0a2f643e-afb3-4189-9a6e-94d0a7884a62',
        is_boj_verified: true,
        boj_solution_id: '83078059',
        created_at: '2024-08-28T02:19:23.251189',
        updated_at: '2024-08-28T02:19:23.251205',
        deleted_at: null,
        status_label: '',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 12,
      username: 'naya_h1',
      nickname: '안희원',
      boj_id: 'naya_h1',
      is_active: true,
      created_at: '2024-08-23T19:10:25.121509',
      updated_at: '2024-08-24T08:34:09.721068',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 1819,
        member: {
          id: 12,
          username: 'naya_h1',
          nickname: '안희원',
          boj_id: 'naya_h1',
          is_active: true,
          created_at: '2024-08-23T19:10:25.121509',
          updated_at: '2024-08-24T08:34:09.721068',
          deleted_at: null,
        },
        problem: {
          id: 1456,
          name: '통과한문제에요',
          boj_id: '9017',
          level: 'silver_3',
          created_at: '2024-08-27T04:03:41.316678',
          updated_at: '2024-08-27T04:03:41.316728',
          is_solved: true,
          is_starred: true,
          stars: 4,
          tags: [
            {
              id: 15,
              name: '구현',
              boj_tag_id: '102',
            },
          ],
          label: '9017 크로스 컨트리',
          url: 'https://ps-note-client.kodori.dev/problem/1456',
          solutions: 2,
        },
        comment: '## 아이디어\n\n💡 고려해야 할 포인트들이 너무 많아서 까다로웠던 문제 ,,,🥹🥲\n\n## 코멘트\n\n',
        source_lang: 'python',
        source_code:
          't = int(input());\nfor i in range(t):\n    n = int(input());\n    team = {}; #팀: 멤버 수\n    memList = list(map(int, input().split()));\n    for j in memList:\n        if j in team:\n            team[j] += 1;\n        else: team[j] = 1;\n\n    score = {}; #팀: 점수\n    five = {}; #팀: 5등 점수\n    rank = 1;\n    res = []; #결승선 통과한 순서\n    for j in memList:\n        if team[j] < 6: continue;\n        if team[j] - 6 == 4: five[j] = rank;\n        if team[j] - 6 < 4:\n            if j in score: score[j] += rank;\n            else: score[j] = rank;\n        if team[j] - 6 == 3: res.append([score[j], j]); \n        team[j] += 1;\n        rank += 1;\n\n    res.sort(key=lambda x:x[0]);\n    \n    if len(res) >= 2 and res[0][0] == res[1][0] and five[res[0][1]] > five[res[1][1]]: print(res[1][1]);\n    else: print(res[0][1]);\n',
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: true,
        is_fully_parsed: false,
        notion_page_id: '90ab6266-ca05-454a-9a0e-df5bf98c1650',
        is_boj_verified: false,
        boj_solution_id: null,
        created_at: '2024-08-28T02:19:26.616045',
        updated_at: '2024-08-28T02:19:26.616091',
        deleted_at: null,
        status_label: '백준 연동 실패',
        score_label: 'AC',
      },
      {
        id: 1819,
        member: {
          id: 12,
          username: 'naya_h1',
          nickname: '안희원',
          boj_id: 'naya_h1',
          is_active: true,
          created_at: '2024-08-23T19:10:25.121509',
          updated_at: '2024-08-24T08:34:09.721068',
          deleted_at: null,
        },
        problem: {
          id: 1456,
          name: '통과한문제에요',
          boj_id: '9017',
          level: 'silver_3',
          created_at: '2024-08-27T04:03:41.316678',
          updated_at: '2024-08-27T04:03:41.316728',
          is_solved: true,
          is_starred: true,
          stars: 4,
          tags: [
            {
              id: 15,
              name: '구현',
              boj_tag_id: '102',
            },
          ],
          label: '9017 크로스 컨트리',
          url: 'https://ps-note-client.kodori.dev/problem/1456',
          solutions: 2,
        },
        comment: '## 아이디어\n\n💡 고려해야 할 포인트들이 너무 많아서 까다로웠던 문제 ,,,🥹🥲\n\n## 코멘트\n\n',
        source_lang: 'python',
        source_code:
          't = int(input());\nfor i in range(t):\n    n = int(input());\n    team = {}; #팀: 멤버 수\n    memList = list(map(int, input().split()));\n    for j in memList:\n        if j in team:\n            team[j] += 1;\n        else: team[j] = 1;\n\n    score = {}; #팀: 점수\n    five = {}; #팀: 5등 점수\n    rank = 1;\n    res = []; #결승선 통과한 순서\n    for j in memList:\n        if team[j] < 6: continue;\n        if team[j] - 6 == 4: five[j] = rank;\n        if team[j] - 6 < 4:\n            if j in score: score[j] += rank;\n            else: score[j] = rank;\n        if team[j] - 6 == 3: res.append([score[j], j]); \n        team[j] += 1;\n        rank += 1;\n\n    res.sort(key=lambda x:x[0]);\n    \n    if len(res) >= 2 and res[0][0] == res[1][0] and five[res[0][1]] > five[res[1][1]]: print(res[1][1]);\n    else: print(res[0][1]);\n',
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: true,
        is_fully_parsed: false,
        notion_page_id: '90ab6266-ca05-454a-9a0e-df5bf98c1650',
        is_boj_verified: false,
        boj_solution_id: null,
        created_at: '2024-08-28T02:19:26.616045',
        updated_at: '2024-08-28T02:19:26.616091',
        deleted_at: null,
        status_label: '백준 연동 실패',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [
      {
        id: 1819,
        member: {
          id: 12,
          username: 'naya_h1',
          nickname: '안희원',
          boj_id: 'naya_h1',
          is_active: true,
          created_at: '2024-08-23T19:10:25.121509',
          updated_at: '2024-08-24T08:34:09.721068',
          deleted_at: null,
        },
        problem: {
          id: 1456,
          name: '크로스 컨트리',
          boj_id: '9017',
          level: 'silver_3',
          created_at: '2024-08-27T04:03:41.316678',
          updated_at: '2024-08-27T04:03:41.316728',
          is_solved: true,
          is_starred: true,
          stars: 4,
          tags: [
            {
              id: 15,
              name: '구현',
              boj_tag_id: '102',
            },
          ],
          label: '9017 크로스 컨트리',
          url: 'https://ps-note-client.kodori.dev/problem/1456',
          solutions: 2,
        },
        comment: '## 아이디어\n\n💡 고려해야 할 포인트들이 너무 많아서 까다로웠던 문제 ,,,🥹🥲\n\n## 코멘트\n\n',
        source_lang: 'python',
        source_code:
          't = int(input());\nfor i in range(t):\n    n = int(input());\n    team = {}; #팀: 멤버 수\n    memList = list(map(int, input().split()));\n    for j in memList:\n        if j in team:\n            team[j] += 1;\n        else: team[j] = 1;\n\n    score = {}; #팀: 점수\n    five = {}; #팀: 5등 점수\n    rank = 1;\n    res = []; #결승선 통과한 순서\n    for j in memList:\n        if team[j] < 6: continue;\n        if team[j] - 6 == 4: five[j] = rank;\n        if team[j] - 6 < 4:\n            if j in score: score[j] += rank;\n            else: score[j] = rank;\n        if team[j] - 6 == 3: res.append([score[j], j]); \n        team[j] += 1;\n        rank += 1;\n\n    res.sort(key=lambda x:x[0]);\n    \n    if len(res) >= 2 and res[0][0] == res[1][0] and five[res[0][1]] > five[res[1][1]]: print(res[1][1]);\n    else: print(res[0][1]);\n',
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: true,
        is_fully_parsed: false,
        notion_page_id: '90ab6266-ca05-454a-9a0e-df5bf98c1650',
        is_boj_verified: false,
        boj_solution_id: null,
        created_at: '2024-08-28T02:19:26.616045',
        updated_at: '2024-08-28T02:19:26.616091',
        deleted_at: null,
        status_label: '백준 연동 실패',
        score_label: 'AC',
      },
    ],
    coupons: [
      {
        id: 14,
        name: '면제쿠폰',
        member: {
          id: 12,
          username: 'naya_h1',
          nickname: '안희원',
          boj_id: 'naya_h1',
          is_active: true,
          created_at: '2024-08-23T19:10:25.121509',
          updated_at: '2024-08-24T08:34:09.721068',
          deleted_at: null,
        },
        used_at: '2024-08-27T00:00:00',
        valid_to: '2024-09-02T00:00:00',
        valid_from: '2024-08-26T00:00:00',
        created_at: '2024-08-27T02:04:20',
        updated_at: '2024-08-27T02:04:20',
      },
    ],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 13,
      username: null,
      nickname: '이서연',
      boj_id: 'godda',
      is_active: true,
      created_at: '2024-08-23T19:10:37.987494',
      updated_at: '2024-08-23T19:15:54.523124',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 1813,
        member: {
          id: 13,
          username: null,
          nickname: '이서연',
          boj_id: 'godda',
          is_active: true,
          created_at: '2024-08-23T19:10:37.987494',
          updated_at: '2024-08-23T19:15:54.523124',
          deleted_at: null,
        },
        problem: {
          id: 317,
          name: 'UNIST는 무엇의 약자일까?',
          boj_id: '17841',
          level: 'gold_3',
          created_at: '2024-08-23T19:15:28.555113',
          updated_at: '2024-08-23T19:15:28.555144',
          is_solved: false,
          is_starred: false,
          stars: 0,
          tags: [
            {
              id: 19,
              name: '다이나믹 프로그래밍',
              boj_tag_id: '25',
            },
          ],
          label: '17841 UNIST는 무엇의 약자일까?',
          url: 'https://ps-note-client.kodori.dev/problem/317',
          solutions: 3,
        },
        comment: '## 아이디어\n\n💡 부분 문자열을 만들 수 있는 개수 \n\n## 코멘트\n\n',
        source_lang: 'kotlin',
        source_code:
          'package org.example\n\nimport java.io.BufferedReader\nimport java.io.InputStreamReader\n\nfun findMatchingPrefix(str: String, target: String): String {\n    var match = ""\n    var j = 0\n    var i = 0\n    while(i < 5 && j < str.length){\n        if(j != 0 && str[j] != target[i]){\n            return match\n        }\n\n        if(str[j] == target[i]){\n            match += str[j]\n            i += 1\n            j += 1\n        }\n        else {\n            i += 1\n        }\n    }\n\n    return match\n}\n\n\nfun main(){\n    val br = BufferedReader(InputStreamReader(System.`in`))\n    val n = br.readLine().toInt()\n    val dp = MutableList(5) { 0L }\n    val target = "UNIST"\n\n    repeat(n){\n        val str = br.readLine()\n        val match = findMatchingPrefix(str, target)\n        if(match.isNotBlank()){\n            val firstLetter = match[0]\n            val value = if(firstLetter == \'U\') 1 else dp[target.indexOf(firstLetter)-1]\n            for(c in match){\n                val index = target.indexOf(c)\n                dp[index] = (dp[index] + value) % 1000000007\n            }\n        }\n    }\n    println(dp[4] % 1000000007)\n\n}\n\n\n\n\n',
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: true,
        is_fully_parsed: true,
        notion_page_id: '6be2aab8-832f-4fc2-89f7-1aaa3566d9a2',
        is_boj_verified: true,
        boj_solution_id: '83074170',
        created_at: '2024-08-28T02:19:23.979469',
        updated_at: '2024-08-28T02:19:23.979507',
        deleted_at: null,
        status_label: '',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 14,
      username: null,
      nickname: '정은교',
      boj_id: 'hithere1003',
      is_active: true,
      created_at: '2024-08-23T19:11:02.964605',
      updated_at: '2024-08-24T08:27:29.880367',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 1812,
        member: {
          id: 14,
          username: null,
          nickname: '정은교',
          boj_id: 'hithere1003',
          is_active: true,
          created_at: '2024-08-23T19:11:02.964605',
          updated_at: '2024-08-24T08:27:29.880367',
          deleted_at: null,
        },
        problem: {
          id: 1518,
          name: '수들의 합 5',
          boj_id: '2018',
          level: 'silver_5',
          created_at: '2024-08-28T02:19:21.490820',
          updated_at: '2024-08-28T02:19:21.490872',
          is_solved: false,
          is_starred: false,
          stars: 0,
          tags: [
            {
              id: 7,
              name: '수학',
              boj_tag_id: '124',
            },
            {
              id: 42,
              name: '두 포인터',
              boj_tag_id: '80',
            },
          ],
          label: '2018 수들의 합 5',
          url: 'https://ps-note-client.kodori.dev/problem/1518',
          solutions: 1,
        },
        comment: '## 아이디어\n\n💡 투 포인터\n\n## 코멘트\n\n',
        source_lang: 'c++',
        source_code:
          '#include <iostream>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n\tios::sync_with_stdio(false);\n\tcin.tie(NULL);\t\n\tcout.tie(NULL);\n\n\tint N;\n\tint start = 1;\n\tint end = 1;\n\tint count = 1;\n\tint sum = 1;\n\t\n\tcin >> N;\n\n\twhile(end != N) {\n\t\tif(sum == N) {\n\t\t\tend++;\n\t\t\tsum = sum + end;\n\t\t\tcount++;\n\t\t}\n\n\t\telse if (sum > N) {\n\t\t\tsum = sum - start;\n\t\t\tstart++;\n\t\t}\n\n\t\telse {\n\t\t\tend++;\n\t\t\tsum = sum + end;\n\t\t}\n\t}\n\n\tcout << count << "\\n";\n}',
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: true,
        is_fully_parsed: true,
        notion_page_id: 'f3349853-3e89-4fa8-a03d-12a46ef47e55',
        is_boj_verified: true,
        boj_solution_id: '83078317',
        created_at: '2024-08-28T02:19:23.625790',
        updated_at: '2024-08-28T02:19:23.625806',
        deleted_at: null,
        status_label: '',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-27',
    member: {
      id: 15,
      username: null,
      nickname: '조경진',
      boj_id: 'kyoungjin',
      is_active: true,
      created_at: '2024-08-23T19:12:59.197072',
      updated_at: '2024-08-24T08:27:30.309402',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 1817,
        member: {
          id: 15,
          username: null,
          nickname: '조경진',
          boj_id: 'kyoungjin',
          is_active: true,
          created_at: '2024-08-23T19:12:59.197072',
          updated_at: '2024-08-24T08:27:30.309402',
          deleted_at: null,
        },
        problem: {
          id: 951,
          name: '헌내기는 친구가 필요해',
          boj_id: '21736',
          level: 'silver_2',
          created_at: '2024-08-25T07:30:10.331412',
          updated_at: '2024-08-25T07:30:10.331494',
          is_solved: false,
          is_starred: false,
          stars: 0,
          tags: [
            {
              id: 3,
              name: '그래프 이론',
              boj_tag_id: '7',
            },
            {
              id: 9,
              name: '너비 우선 탐색',
              boj_tag_id: '126',
            },
            {
              id: 11,
              name: '그래프 탐색',
              boj_tag_id: '11',
            },
            {
              id: 30,
              name: '깊이 우선 탐색',
              boj_tag_id: '127',
            },
          ],
          label: '21736 헌내기는 친구가 필요해',
          url: 'https://ps-note-client.kodori.dev/problem/951',
          solutions: 2,
        },
        comment:
          '## 아이디어\n\n💡 상하좌우가 간선으로 연결된 정점이라고 생각하고 DFS\n\n## 코멘트\n\ndfs로 성공하고 구글링했더니 다들 bfs로 풀었네요\n\ndfs 말고 bfs로 푸는 이유가 따로 있는걸까요..?\n\n한번에 성공해서 뿌듯합니당..\n\n',
        source_lang: 'c++',
        source_code:
          "#define _CRT_SECURE_NO_WARNINGS\n#include <iostream>\nusing namespace std;\n\nchar campus[601][601];\nint visited[601][601];\nint n, m;\nint res = 0;\n\nvoid dfs(int x, int y) {\n\tvisited[x][y] = 1;\n\tif (campus[x][y] == 'P') res++;\t// 사람이면 카운트\n\n\t// 상\n\tif ((x - 1 >= 0) && campus[x - 1][y] != 'X') {\n\t\tif (!visited[x - 1][y]) dfs(x - 1, y);\n\t}\n\t// 하\n\tif ((x + 1 < n) && campus[x + 1][y] != 'X') {\n\t\tif (!visited[x + 1][y]) dfs(x + 1, y);\n\t}\n\t// 좌\n\tif ((y - 1 >= 0) && campus[x][y - 1] != 'X') {\n\t\tif (!visited[x][y - 1]) dfs(x, y - 1);\n\t}\n\t// 우\n\tif ((y + 1 < m) && campus[x][y + 1] != 'X') {\n\t\tif (!visited[x][y + 1]) dfs(x, y + 1);\n\t}\n}\n\nint main() {\n\tios_base::sync_with_stdio(0);\n\tcin.tie(0);\n\n\tcin >> n >> m;\n\n\t// get inputs\n\tint my_x, my_y;\n\tfor (int i = 0; i < n; i++) {\n\t\tfor (int j = 0; j < m; j++) {\n\t\t\tchar info;\n\t\t\tcin >> info;\n\t\t\tif (info == 'I') {\n\t\t\t\tmy_x = i;\n\t\t\t\tmy_y = j;\n\t\t\t}\n\t\t\tcampus[i][j] = info;\n\t\t}\n\t}\n\n\tdfs(my_x, my_y);\n\n\tif (!res) cout << \"TT\";\n\telse cout << res;\n\n\treturn 0;\n}",
        is_correct_answer: true,
        submitted_at: '2024-08-27',
        imported_from_notion: true,
        is_fully_parsed: true,
        notion_page_id: '4c1a2614-4a0b-4de8-9c5d-f5e57e5cf40d',
        is_boj_verified: true,
        boj_solution_id: '83067680',
        created_at: '2024-08-28T02:19:25.824780',
        updated_at: '2024-08-28T02:19:25.824804',
        deleted_at: null,
        status_label: '',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
];

export const WEEK_PENALTY = [
  {
    day: '2024-08-20',
    member: {
      id: 12,
      username: 'naya_h1',
      nickname: '안희원',
      boj_id: 'naya_h1',
      is_active: true,
      created_at: '2024-08-23T19:10:25.121509',
      updated_at: '2024-08-24T08:34:09.721068',
      deleted_at: null,
    },
    amount: '5000.00',
    admitted_solutions: [],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: true,
    manually_edited: false,
  },
  {
    day: '2024-08-21',
    member: {
      id: 12,
      username: 'naya_h1',
      nickname: '안희원',
      boj_id: 'naya_h1',
      is_active: true,
      created_at: '2024-08-23T19:10:25.121509',
      updated_at: '2024-08-24T08:34:09.721068',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 559,
        member: {
          id: 12,
          username: 'naya_h1',
          nickname: '안희원',
          boj_id: 'naya_h1',
          is_active: true,
          created_at: '2024-08-23T19:10:25.121509',
          updated_at: '2024-08-24T08:34:09.721068',
          deleted_at: null,
        },
        problem: {
          id: 332,
          name: '등수 구하기',
          boj_id: '1205',
          level: 'silver_4',
          created_at: '2024-08-23T19:16:15.205421',
          updated_at: '2024-08-24T18:44:42.255856',
          is_solved: true,
          is_starred: false,
          stars: 0,
          tags: [
            {
              id: 15,
              name: '구현',
              boj_tag_id: '102',
            },
          ],
          label: '1205 등수 구하기',
          url: 'https://ps-note-client.kodori.dev/problem/332',
          solutions: 1,
        },
        comment: '## 아이디어\n\n💡 n의 범위가 50 이하이므로 그냥 찾자 ~\n\n## 코멘트\n\n',
        source_lang: 'javascript',
        source_code:
          "const fs = require('fs');\nconst filePath = process.platform === 'linux' ? '/dev/stdin' : './input.txt';\nlet input = fs.readFileSync(filePath).toString().split('\\n');\n\nconst [n, s, p] = input[0].split(' ').map(Number);\nif (n == 0) {\n  console.log(1);\n  process.exit(0);\n}\n\ninput = input[1]\n  .split(' ')\n  .map(Number)\n  .sort((a, b) => b - a);\n\nif (n == p && input[n - 1] >= s) {\n  console.log(-1);\n  process.exit(0);\n}\n\nlet ans = 1;\nfor (let i = 0; i < n; i++) {\n  if (input[i] < s) {\n    console.log(input[i - 1] === s ? ans : i + 1);\n    process.exit(0);\n  }\n  if (i > 0 && input[i - 1] !== input[i]) ans = i + 1;\n}\n\nconsole.log(input[n - 1] === s ? ans : n + 1);\n",
        is_correct_answer: true,
        submitted_at: '2024-08-21',
        imported_from_notion: true,
        is_fully_parsed: true,
        notion_page_id: '35a4c485-20d8-4b6b-b029-afd4faa1e987',
        is_boj_verified: true,
        boj_solution_id: '82803393',
        created_at: '2024-08-23T19:16:15.731872',
        updated_at: '2024-08-24T21:01:07.744072',
        deleted_at: null,
        status_label: '',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-22',
    member: {
      id: 12,
      username: 'naya_h1',
      nickname: '안희원',
      boj_id: 'naya_h1',
      is_active: true,
      created_at: '2024-08-23T19:10:25.121509',
      updated_at: '2024-08-24T08:34:09.721068',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 562,
        member: {
          id: 12,
          username: 'naya_h1',
          nickname: '안희원',
          boj_id: 'naya_h1',
          is_active: true,
          created_at: '2024-08-23T19:10:25.121509',
          updated_at: '2024-08-24T08:34:09.721068',
          deleted_at: null,
        },
        problem: {
          id: 335,
          name: '임스와 함께하는 미니게임',
          boj_id: '25757',
          level: 'silver_5',
          created_at: '2024-08-23T19:16:24.544312',
          updated_at: '2024-08-26T07:45:02.434456',
          is_solved: true,
          is_starred: false,
          stars: 0,
          tags: [
            {
              id: 2,
              name: '자료 구조',
              boj_tag_id: '175',
            },
            {
              id: 20,
              name: '해시를 사용한 집합과 맵',
              boj_tag_id: '136',
            },
            {
              id: 39,
              name: '문자열',
              boj_tag_id: '158',
            },
          ],
          label: '25757 임스와 함께하는 미니게임',
          url: 'https://ps-note-client.kodori.dev/problem/335',
          solutions: 2,
        },
        comment: '## 아이디어\n\n💡 중복 제거는 역시 집합으로 ~!\n\n## 코멘트\n\n',
        source_lang: 'python',
        source_code:
          "GAME = {\n    'Y':2,\n    'F':3,\n    'O':4};\n\n[n, t] = input().split();\n\nperson = set();\n\nfor i in range(int(n)):\n    name = input();\n    person.add(name);\n\nprint(len(person)//(GAME[t]-1));",
        is_correct_answer: true,
        submitted_at: '2024-08-22',
        imported_from_notion: true,
        is_fully_parsed: false,
        notion_page_id: 'ba385564-dad1-454c-bb04-1448da5af0e0',
        is_boj_verified: true,
        boj_solution_id: '82861617',
        created_at: '2024-08-23T19:16:25.075451',
        updated_at: '2024-08-24T21:01:00.465786',
        deleted_at: null,
        status_label: '',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
  {
    day: '2024-08-23',
    member: {
      id: 12,
      username: 'naya_h1',
      nickname: '안희원',
      boj_id: 'naya_h1',
      is_active: true,
      created_at: '2024-08-23T19:10:25.121509',
      updated_at: '2024-08-24T08:34:09.721068',
      deleted_at: null,
    },
    amount: '0.00',
    admitted_solutions: [
      {
        id: 570,
        member: {
          id: 12,
          username: 'naya_h1',
          nickname: '안희원',
          boj_id: 'naya_h1',
          is_active: true,
          created_at: '2024-08-23T19:10:25.121509',
          updated_at: '2024-08-24T08:34:09.721068',
          deleted_at: null,
        },
        problem: {
          id: 318,
          name: '스위치 켜고 끄기',
          boj_id: '1244',
          level: 'silver_4',
          created_at: '2024-08-23T19:15:28.793735',
          updated_at: '2024-08-26T19:56:26.741929',
          is_solved: true,
          is_starred: true,
          stars: 1,
          tags: [
            {
              id: 15,
              name: '구현',
              boj_tag_id: '102',
            },
            {
              id: 16,
              name: '시뮬레이션',
              boj_tag_id: '141',
            },
          ],
          label: '1244 스위치 켜고 끄기',
          url: 'https://ps-note-client.kodori.dev/problem/318',
          solutions: 2,
        },
        comment: '## 아이디어\n\n💡 대칭 확인할 때 범위 잘 체크하기\n\n## 코멘트\n\n',
        source_lang: 'python',
        source_code:
          'n = int(input()); #스위치 개수\ns = list(map(int, input().split())); #스위치 상태\nnum = int(input());\nfor i in range(num):\n    [x, y] = list(map(int, input().split()));\n    if(x == 1):\n        for j in range(y-1, n, y):\n            s[j] ^= 1;\n    \n    if(x == 2):\n        y -= 1;\n        s[y] ^= 1;\n        idx = 1;\n        while(0 <= y-idx and y+idx < n):\n            #print(y-idx, y+idx);\n            if(s[y-idx] != s[y+idx]): break;\n            s[y-idx] ^= 1;\n            s[y+idx] ^= 1;\n            idx += 1;\n    #print(s);\nfor i in range(n):\n    print(s[i], end=" ");\n    if(i and (i+1)%20 == 0):\n        print();\n',
        is_correct_answer: true,
        submitted_at: '2024-08-23',
        imported_from_notion: true,
        is_fully_parsed: true,
        notion_page_id: '267bb4f7-1d40-4033-914e-78f8046ca87b',
        is_boj_verified: true,
        boj_solution_id: '82895000',
        created_at: '2024-08-23T19:16:31.882633',
        updated_at: '2024-08-24T21:00:49.749009',
        deleted_at: null,
        status_label: '',
        score_label: 'AC',
      },
    ],
    not_admitted_solutions: [],
    coupons: [],
    is_penalty: false,
    manually_edited: false,
  },
];

export const HOLIDAY = [
  {
    id: 1,
    name: '1월1일',
    date: '2024-01-01',
  },
  {
    id: 2,
    name: '설날',
    date: '2024-02-09',
  },
  {
    id: 3,
    name: '설날',
    date: '2024-02-10',
  },
  {
    id: 4,
    name: '설날',
    date: '2024-02-11',
  },
  {
    id: 5,
    name: '대체공휴일(설날)',
    date: '2024-02-12',
  },
  {
    id: 6,
    name: '삼일절',
    date: '2024-03-01',
  },
  {
    id: 7,
    name: '국회의원선거',
    date: '2024-04-10',
  },
  {
    id: 8,
    name: '어린이날',
    date: '2024-05-05',
  },
  {
    id: 9,
    name: '대체공휴일(어린이날)',
    date: '2024-05-06',
  },
  {
    id: 10,
    name: '부처님오신날',
    date: '2024-05-15',
  },
  {
    id: 11,
    name: '현충일',
    date: '2024-06-06',
  },
  {
    id: 12,
    name: '광복절',
    date: '2024-08-15',
  },
  {
    id: 13,
    name: '추석',
    date: '2024-09-16',
  },
  {
    id: 14,
    name: '추석',
    date: '2024-09-17',
  },
  {
    id: 15,
    name: '추석',
    date: '2024-09-18',
  },
  {
    id: 16,
    name: '개천절',
    date: '2024-10-03',
  },
  {
    id: 17,
    name: '한글날',
    date: '2024-10-09',
  },
  {
    id: 18,
    name: '기독탄신일',
    date: '2024-12-25',
  },
];
