name: Build and Push Docker Image to Google Artifact Registry

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      GCP_REGISTRY: asia-northeast3-docker.pkg.dev/cnu-k8s
      GCP_REPOSITORY: ps-note/ps-note-client
      IMAGE_TAG: ${{ github.sha }}
      NEXT_PUBLIC_API_BASE_URL: ps-note-server

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Artifact Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.GCP_REGISTRY }}
        username: _json_key
        password: ${{ secrets.GCP_CREDENTIALS }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.GCP_REGISTRY }}/${{ env.GCP_REPOSITORY }}
        tags: |
          type=sha
          latest

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile
        build-args: |
          NEXT_PUBLIC_API_BASE_URL=${{ env.NEXT_PUBLIC_API_BASE_URL }}
        push: true
        platforms: |
          linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ env.GCP_REGISTRY }}/${{ env.GCP_REPOSITORY }}:cache
        cache-to: type=registry,ref=${{ env.GCP_REGISTRY }}/${{ env.GCP_REPOSITORY }}:cache,mode=max